### ISSUE TITLE
enh: Do not rely on discovery.etcd.io, use AWS metadata to bootstrap

### ISSUE THREAD

**Issue by pmoust** [giantswarm/kocho#41]
Inspired from https://github.com/MonsantoCo/etcd-aws-cluster/blob/develop/etcd-aws-cluster 

We use the following cloud-init to provision our etcd clusters and we find it much better to rely on AWS metadata rather than a public service with no guarantees on.

``` yaml
#cloud-config

coreos:
  etcd2:
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
  fleet:
    public-ip: $private_ipv4
    etcd_servers: "${peers}"
  update:
    group: ${channel}
    reboot-strategy: ${reboot-strategy}
  units:
    - name: docker.service
      runtime: true
      command: start

    # etcd and fleet are initially stopped. We'll start them when the peers have been calculated
    - name: etcd2.service
      command: stop
    - name: fleet.service
      command: stop

    - name: etcd-peers.service
      command: start
      content: |
        [Unit]
        Description=Write a file with the etcd peers that we should bootstrap to
        After=docker.service
        [Service]
        Restart=on-failure
        RestartSec=10
        EnvironmentFile=/etc/environment
        ExecStartPre=/usr/bin/docker pull peopleperhour/etcd-aws-cluster:latest
        ExecStartPre=/usr/bin/docker run --rm=true -v /etc/sysconfig/:/etc/sysconfig/ peopleperhour/etcd-aws-cluster:latest
        ExecStart=/usr/bin/systemctl start etcd2

    # Query AWS metadata service when this EC2 instance starts to get info about instance's self. e.g. IP address.
    - name: fleet-metadata.service
      runtime: true
      command: start
      content: |-
        [Unit]
        Description=Inject EC2 Metadata into Fleet
        After=docker.service
        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        ExecStartPre=/usr/bin/docker pull peopleperhour/ec2-metadata
        ExecStart=/usr/bin/bash -c '\
          mkdir -p /run/systemd/system/fleet.service.d; \
          conf_file=/run/systemd/system/fleet.service.d/666-ec2-metadata.conf; \
          zone=$(docker run --rm peopleperhour/ec2-metadata -z   | sed "s/: /=/g"); \
          id=$(docker run --rm peopleperhour/ec2-metadata -i     | sed "s/: /=/g"); \
          ip=$(docker run --rm peopleperhour/ec2-metadata -v     | sed "s/: /=/g" | sed "s/ /_/g"); \
          type=$(docker run --rm peopleperhour/ec2-metadata -t   | sed "s/: /=/g"); \
          echo "[Service]" > $conf_file; \
          echo "Environment=FLEET_METADATA=role=${role},$ip,$id,$type,$zone"  >> $conf_file;'

    - name: fleet-reloaded.service
      command: start
      content: |
        [Unit]
        Description=Ensure fleet starts with updated metadata
        After=docker.service
        After=fleet-metadata.service
        [Service]
        Restart=on-failure
        RestartSec=10
        EnvironmentFile=/etc/environment
        ExecStartPre=/usr/bin/systemctl daemon-reload
        ExecStart=/usr/bin/systemctl start fleet
write_files:
    # Pre-configure the core user with authentication to our private Docker Hub repo (as the pphrobot hub user).
    - path: /home/core/.dockercfg
      owner: core:core
      permissions: 0644
      content: |
        {"https://index.docker.io/v1/":{"auth":"snipped","email":"devops@peopleperhour.com"}}
    - path: /etc/systemd/system/etcd2.service.d/30-etcd_peers.conf
      permissions: 0644
      content: |
        [Service]
        EnvironmentFile=/etc/sysconfig/etcd-peers

users:
  - name: pmoust
    coreos-ssh-import-github: pmoust
    groups:
      - sudo
      - docker
      - wheel
  - name: core
    coreos-ssh-import-github-users:
      - pmoust

manage_etc_hosts: localhost
```
